
package com.epamacademy.webservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CannotAddDataException", targetNamespace = "http://service.webservice.epamacademy.com/")
public class CannotAddDataException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CannotAddDataException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CannotAddDataException_Exception(String message, CannotAddDataException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CannotAddDataException_Exception(String message, CannotAddDataException faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epamacademy.webservice.service.CannotAddDataException
     */
    public CannotAddDataException getFaultInfo() {
        return faultInfo;
    }

}
