
package com.epamacademy.webservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DBAccessException", targetNamespace = "http://service.webservice.epamacademy.com/")
public class DBAccessException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DBAccessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DBAccessException_Exception(String message, DBAccessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DBAccessException_Exception(String message, DBAccessException faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epamacademy.webservice.service.DBAccessException
     */
    public DBAccessException getFaultInfo() {
        return faultInfo;
    }

}
